Add bucket-related operations
skyplane-project/skystore pull request #26
Opened 2023-07-06 19:21 UTC by lynnliu030

2023-07-18 17:22 UTC, simon-mo requested changes
It seems like this PR are doing many things:
- Bucket operations (not fully done)
- CLI (this is nice but needs a separate design, we can also write it in Python if that's easier?)
- Configuration system so it is not hard coded. 

Let's do smaller PR first?

2023-07-18 17:22 UTC, simon-mo commented on README.md
> +Before E2E test, if make changes to the server, then run
```suggestion
Before E2E test, if make changes to the server's API, then run the following to re-generate the rust client code. 
```

2023-07-18 17:22 UTC, simon-mo commented on config/init_config.json
> +{
move theses to a test or example folder

2023-07-18 17:22 UTC, simon-mo commented on s3-proxy/src/.DS_Store
remove this. i also added ignoring .DS_Store to the main branch.

2023-07-18 17:22 UTC, simon-mo commented on s3-proxy/src/client_impls/gcp.rs
> +        Ok(S3Response::new(HeadBucketOutput::default()))
This need to be fixed and tested

2023-07-18 17:22 UTC, simon-mo commented on s3-proxy/src/client_impls/azure.rs
> +            Ok(_) => Ok(S3Response::new(HeadBucketOutput::default())),
This need to be fixed and tested.

2023-07-18 17:22 UTC, simon-mo commented on s3-proxy/src/skyproxy.rs
> +    async fn warmup(
wait what does this do?

2023-07-18 18:01 UTC, lynnliu030 commented on s3-proxy/src/skyproxy.rs
> +    async fn warmup(
just removed that! used for testing

2023-09-13 22:22 UTC, simon-mo approved these changes

2023-09-13 22:22 UTC, simon-mo commented on s3-proxy/src/skyproxy.rs
> +        // Real object store configuration (regions: init regions)
Assuming this will be brought back?

2023-09-13 22:22 UTC, simon-mo commented on s3-proxy/src/skyproxy.rs
> +            // if buckt name starts with skystore-, then it's a skybucket already created during initialization
Can you explain? When do we create such bucket?

2023-09-13 22:22 UTC, simon-mo commented on s3-proxy/src/skyproxy.rs
> +                    s3s::S3ErrorCode::InternalError,
Leave a todo to handle cleanup the others if only one failed?

2023-09-13 22:58 UTC, lynnliu030 commented on s3-proxy/src/skyproxy.rs
> +        // Real object store configuration (regions: init regions)
yes, this part is for real object-store testing

2023-09-13 23:00 UTC, lynnliu030 commented on s3-proxy/src/skyproxy.rs
> +            // if buckt name starts with skystore-, then it's a skybucket already created during initialization
This is creating empty buckets in all init regions to store cache copies later; I guess we can also do bucket creation later when cache copies are created, but this is just for convenience

2023-09-13 23:16 UTC, merged