Issue #30: cleanup metadata on timeout
skyplane-project/skystore pull request #44
Opened 2023-10-19 23:20 UTC by HenricZh

Added a background task to remove the locks held by timed-out operations for creating/deleting objects and buckets. Done using asyncio. Inside a while loop, there is the logic to handle removing locks and then a sleep call to force the process to wait for 10 minutes. 10 minutes is currently hard coded into the start-up process for the fastapi app.

2023-10-25 01:09 UTC, lynnliu030 requested changes

2023-10-25 07:43 UTC, HenricZh commented on store-server/object_models.py
> +    status: Optional[Status] = None
removed status from response. Created new response and routes so I can test the background task.

2023-10-25 07:44 UTC, HenricZh commented on store-server/app.py
> +            lock_acquired_at=None,
Changed from lock_acquired_at -> lock_acquired_ts

2023-10-26 17:01 UTC, lynnliu030 commented
Need to reformat via `black .`, `ruff .`, and `cargo fmt`, take a look at the workflow and where it fails

2023-10-29 00:27 UTC, lynnliu030 commented on store-server/app.py
> +#         title="Custom title",
Can you remove these?

2023-10-29 00:27 UTC, lynnliu030 commented on store-server/test_app.py
> +    #     resp.raise_for_status()
Remove these?

2023-10-29 00:27 UTC, lynnliu030 commented on store-server/test_app.py
> +    # pytest.set_trace() #debugging line
Remove these lines?

2023-10-29 00:27 UTC, lynnliu030 commented on store-server/app.py
> +    """Given the bucket name, return one or zero physical bucket locators."""
This is just for the test for store-server right? Can you add a comment into it? Also the description should be updated to return the status of the bucket

2023-10-29 00:27 UTC, lynnliu030 commented on store-server/app.py
> +    )
This should be removed, `reason` should be removed as well

2023-10-29 01:02 UTC, HenricZh commented on store-server/app.py
> +#         title="Custom title",
removed

2023-10-29 01:02 UTC, HenricZh commented on store-server/test_app.py
> +    #     resp.raise_for_status()
removed

2023-10-29 01:02 UTC, HenricZh commented on store-server/app.py
> +    """Given the bucket name, return one or zero physical bucket locators."""
Yes, just for testing. I added comments and fixed the description.

2023-10-29 01:02 UTC, HenricZh commented on store-server/app.py
> +    )
Removed

2023-10-30 21:18 UTC, HenricZh commented on store-server/test_app.py
> +    # pytest.set_trace() #debugging line
removed

2023-10-30 22:10 UTC, simon-mo reviewed
How long would the loop block the database? Is it bounded or O(objects). Would it be possible to limit the max number of objects to delete?

2023-10-30 22:10 UTC, simon-mo commented on store-server/app.py
> +    loop.create_task(rm_lock_on_timeout(10))
you need to store the task in a global dictionary otherwise they will get garbage collected. see https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task

2023-10-31 00:35 UTC, HenricZh commented on store-server/app.py
> +    loop.create_task(rm_lock_on_timeout(10))
added a global set to fix this according to the python docs. 

For the previous comment, the loop is O(objects that need to have locks freed). It would be possible to limit the number of objects to delete by sorting and limiting the SQL statements. Sort by time and then remove up to the limit. But, would doing so be good for performance? By limiting, we would be creating an upper bound for how long the loop would take but that would also push back some frees to the next wave. For example, limiting to 10 objects when 11 need to be updated. The last object would have to wait 20 minutes rather than 10 minutes which would hold on to the lock for pretty long.

2023-11-01 00:45 UTC, lynnliu030 approved these changes

2023-11-01 00:45 UTC, merged