Support range copy in s3-proxy upload_part_copy
skyplane-project/skystore pull request #48
Opened 2023-10-24 13:40 UTC by SongShaopu1998

- Support range copy in azure & gcp storage file
- Change skyproxy.rs to match the range content length
- Add a test case with large object size using range copy
- Fix bugs in s3s upload_part_copy function

2023-10-25 01:59 UTC, SongShaopu1998 commented on s3-proxy/src/skyproxy.rs
> +                content_length = end - start + 1;
https://github.com/SongShaopu1998/s3s/blob/main/crates/s3s-fs/src/s3.rs#L567

2023-10-25 02:02 UTC, SongShaopu1998 commented on s3-proxy/Cargo.toml
> +# azure_svc_blobstorage = { git = "https://github.com/Azure/azure-sdk-for-rust.git", rev = "5014404dff3cd77faf37a7077ec67bb6a2cf1f4c" }
Sure, I remove them. These were used to import the azure service library, since I have tried to change the azure sdk to azure service library.

2023-10-25 02:31 UTC, simon-mo commented on s3-proxy/Cargo.toml
> +hex = "0.4.3"
```suggestion
hex = "0.4.3"
```

2023-10-25 02:31 UTC, simon-mo commented on s3-proxy/src/type_utils.rs
> +    // range: e.g. "bytes=0-100"
assert starts with bytes

2023-10-25 02:31 UTC, simon-mo commented on s3-proxy/src/client_impls/gcp.rs
> +            let body = StreamingBlob::wrap(res);
what if this is better than memory? consider assert the content size to <2G or something? alternatively, you can use a temporary file to write the object to.

2023-10-25 02:31 UTC, simon-mo commented on s3-proxy/src/client_impls/azure.rs
> +        if let Some(range) = req.copy_source_range {
You don't need to do this for Azure. put block url support range
> 

x-ms-source-range | Optional. Uploads only the bytes of the blob in the source URL in the specified range. If this header isn't specified, the entire source blob contents are uploaded as a single block. For more information, see Specify the range header for Blob service operations.
-- | --


x-ms-source-range	Optional. Uploads only the bytes of the blob in the source URL in the specified range. If this header isn't specified, the entire source blob contents are uploaded as a single block. For more information, see [Specify the range header for Blob service operations](https://learn.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations).

https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-from-url?tabs=azure-ad

2023-10-25 02:46 UTC, SongShaopu1998 commented on s3-proxy/src/client_impls/azure.rs
> +        if let Some(range) = req.copy_source_range {
I tried to search the range support in azure sdk for rust, but I found that they only support these operations for `put_block_url` now:

```rust
operation! {
    PutBlockUrl,
    client: BlobClient,
    block_id: BlockId,
    url: Url,
    ?hash: Hash,
    ?lease_id: LeaseId
}

impl PutBlockUrlBuilder {
    pub fn into_future(mut self) -> PutBlockUrl {
        Box::pin(async move {
            let mut url = self.client.url()?;

            self.block_id.append_to_url_query(&mut url);
            url.query_pairs_mut().append_pair("comp", "block");

            let mut headers = Headers::new();
            headers.insert(COPY_SOURCE, self.url.to_string());
            headers.add(self.lease_id);

            let mut request =
                BlobClient::finalize_request(url, azure_core::Method::Put, headers, None)?;

            let response = self.client.send(&mut self.context, &mut request).await?;
            PutBlockUrlResponse::from_headers(response.headers())
        })
    }
}
```
And since it creates the header inside the function, I didn't find out a way to pass a range header into this function.

However, I found that azure has the range support for this REST API in their `services` package, [here](https://github.com/Azure/azure-sdk-for-rust/blob/main/services/svc/blobstorage/src/package_2021_12/mod.rs#L14726). Do we need to change the implementation to using Azure services API?

2023-10-25 03:02 UTC, simon-mo commented on s3-proxy/src/client_impls/azure.rs
> +        if let Some(range) = req.copy_source_range {
Yes. Sending a PR to the Azure SDK repo could be useful!

2023-10-25 18:01 UTC, lynnliu030 requested changes

2023-10-25 18:01 UTC, lynnliu030 commented on s3-proxy/justfile
> +    --git https://github.com/SongShaopu1998/s3s \
Your changes have been merged so maybe change back to the released version here: https://github.com/Nugine/s3s/commit/0cc49cf24c05eeb6a809882d1a7b76e953822c0d

2023-10-26 00:59 UTC, SongShaopu1998 commented on s3-proxy/src/client_impls/azure.rs
> +        if let Some(range) = req.copy_source_range {
Sure, my PR has been approved, I will update soon.

2023-10-26 01:01 UTC, SongShaopu1998 commented on s3-proxy/src/client_impls/gcp.rs
> +            let body = StreamingBlob::wrap(res);
For the assertion, do you mean something like this?
```rust
let (start, end) = parse_range(&range);
let max = end.unwrap_or(u64::MAX);
// cutoff is 2GB
let cutoff = 2 * 1024 * 1024 * 1024;
if metadata.size as u64 - start > cutoff && max - start > cutoff {
    panic!(
        "The range is too large, try to reduce the range to be less than 2GB!"
    );
}
```

2023-10-26 08:21 UTC, SongShaopu1998 commented on s3-proxy/justfile
> +    --git https://github.com/SongShaopu1998/s3s \
Done.

2023-10-26 16:47 UTC, lynnliu030 approved these changes

2023-10-26 16:57 UTC, merged