Integrate Policy to Prototype
skyplane-project/skystore pull request #63
Opened 2023-11-26 05:44 UTC by shaopu1225

- Integrate Data placement and data transfer policy to prototype
- Fix GCS delete marker abnormal behavior (GCS does not have delete marker like AWS)

2023-11-26 05:59 UTC, lynnliu030 requested changes

2023-11-26 05:59 UTC, lynnliu030 commented on s3-proxy/justfile
> +  cargo test skyproxy -- --nocapture
Why? change it back

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/object_operations.py
> +from .policy.placement_policy import (
remove `.policy` use `operations.policy`

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/object_operations.py
> +    # self.transfer_policy.get(req)
Remove comments

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +    def get_policy(self) -> str:
Add comments to these functions (input, output), change `get_policy` to something like `def name(self) -> str`

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +            return list(self.total_graph.nodes())
there is no `total_graph` here, have you test all the policies?

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +        # print("type of locators: ", type(physical_bucket_locators))
Remove comments

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +put_policy = PlacementPolicy()
What is this variable used for?

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/transfer_policy.py
> +        # place based on the physical locators
Remove these comments and the comments above; why don't we use the `def get_physical_object_locators` function to calculate the physical locators for the request? why do we need to pass in the list of physical locators here?

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/transfer_policy.py
> +        for locator in physical_locators:
`chosen_locator = min(physical_locators, key=lambda loc: self.stat_graph[client_from_region][loc.location_tag]["cost"])
`

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/transfer_policy.py
> +        # can get the latency of self.stat_graph[client_from_region][region]['latency']
Remove redundant comments and print

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/transfer_policy.py
> +                ]
`chosen_locator = max(
    physical_locators, 
    key=lambda loc: self.stat_graph[client_from_region][loc.location_tag]["throughput"]
)
`

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/policy/utils/test/test.py
> +G = make_nx_graph()
What is this file for? should remove it

2023-11-26 05:59 UTC, lynnliu030 commented on store-server/operations/schemas/object_schemas.py
> +    # policy: Optional[str] = "push"
Just delete instead of commenting it out

2023-11-26 06:27 UTC, shaopu1225 commented on store-server/operations/policy/placement_policy.py
> +put_policy = PlacementPolicy()
This variable is to keep track of the current put_policy, the `update_policy` method will update this variable and the `get_policy` variable defined in `transfer_policy.py`.

2023-12-07 20:26 UTC, lynnliu030 requested changes

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/experiment/trace/trace_output_new.csv
> +2023-12-01 18:09:02,write,aws:eu-central-2,b7c3f4e4,439391083
This file is used for? maybe we can just leave one of these

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/bucket_operations.py
> +    # print("start check time: ", datetime.now())
Remove print (and all comments)

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +        single_store_region = "aws:us-west-1"
Put a note here: hard coded for now; make this a variable init in `def __init__`

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +        push_regions = ["aws:us-west-1", "aws:us-east-1"]
Same things for here

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/policy/placement_policy.py
> +def build_placement_policy_from_name(
`get_policy()` would be enough

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/policy/transfer_policy.py
> +        print("TransferPolicy.get() called")
Remove

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/policy/transfer_policy.py
> +def build_transfer_policy_from_name(name: str) -> TransferPolicy:
same name as above, `get_transfer_policy`

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/schemas/bucket_schemas.py
> +    # id = Column(Integer, primary_key=True, autoincrement=True)
Can you make a note here on the Postgres and SQLite difference?

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/schemas/bucket_schemas.py
> +    # id = Column(Integer, primary_key=True, autoincrement=True)
Or maybe is it better that you just copy the SQLite bucket_schemas file into another file?

2023-12-07 20:26 UTC, lynnliu030 commented on store-server/operations/utils/db.py
> +        # await conn.execute(f"ALTER DATABASE {db_name} SET full_page_writes TO off;")
Make a note here to say these are the optimizations can be applied in VM setup

2023-12-07 22:26 UTC, shaopu1225 commented on store-server/operations/schemas/bucket_schemas.py
> +    # id = Column(Integer, primary_key=True, autoincrement=True)
Sure,  I wll do that.

2023-12-07 22:53 UTC, merged